[package]
name = "dnbradio-bot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dnbradio-bot"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
chrono = "0.4.34"
dotenvy = "0.15.7"
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1.0.80"
serenity = "0.12.0"
irc = { version = "0.15.0", default-features = false, features = ["tls-rust"] }
async-trait = "0.1.77"
futures = "0.3.30"
reqwest = { version = "0.11.24", default-features = false, features = ["json", "rustls-tls"] }
serde = "1.0.197"
serde_json = "1.0.114"
env_logger = "0.11.2"
minimp3 = { version = "0.5.1", features = ["async_tokio"] }
log = "0.4.20"
chfft = "0.3.4"
dasp = { version = "0.11.0", features = ["signal", "interpolate", "interpolate-sinc", "ring_buffer"] }
rand = "0.8.5"
uuid = { version = "1.7.0", features = ["v4"] }
byteorder = "1.5.0"
crc32fast = "1.4.0"
base64 = "0.21.7"
dyn-fmt = "0.4.0"
regex = "1.10.3"
